name: Updater

on:
 schedule:
    - cron: '0 0 * * *'

jobs:
  update-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install httpx beautifulsoup4 httpx[socks]

    - name: Run the command to access my computer for get PlutoItaly.m3u
      run: ${{secrets.COMMAND}}

    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git diff
        git commit -am "Updated links $(date +"%Y-%m-%d %H:%M:%S")" || echo "No changes to commit"
        git push
